In [1]:
from numpy import genfromtxt, zeros
# read the first 4 columns
data = genfromtxt('iris.csv',delimiter=',',usecols=(0,1,2,3))
# read the fifth column
target = genfromtxt('iris.csv',delimiter=',',usecols=(4),dtype=str)
print (data.shape)
print (target.shape)
print (set (target))

(150, 4)
(150,)
{'setosa', 'virginica', 'versicolor'}


In [2]:
t = zeros(len(target))
t[target == 'setosa'] = 1
t[target == 'versicolor'] = 2
t[target == 'virginica'] = 3

## n_estimators=5

In [41]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators=5)

In [42]:
from sklearn import cross_validation
train, test, t_train, t_test = cross_validation.train_test_split(data, t, test_size=0.2, random_state=0)

In [43]:
classifier.fit(train,t_train) # train
print (classifier.score(test,t_test)) # test

0.966666666667


In [44]:
from sklearn.metrics import confusion_matrix
print (confusion_matrix(classifier.predict(test),t_test))


[[11  0  0]
 [ 0 13  1]
 [ 0  0  5]]


In [45]:
from sklearn.metrics import classification_report
print (classification_report(classifier.predict(test), t_test,
target_names=['setosa', 'versicolor', 'virginica']))

             precision    recall  f1-score   support

     setosa       1.00      1.00      1.00        11
 versicolor       1.00      0.93      0.96        14
  virginica       0.83      1.00      0.91         5

avg / total       0.97      0.97      0.97        30



## n_estimators=10

In [36]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators=10)

In [37]:
from sklearn import cross_validation
train, test, t_train, t_test = cross_validation.train_test_split(data, t, test_size=0.2, random_state=0)

In [38]:
classifier.fit(train,t_train) # train
print (classifier.score(test,t_test)) # test

1.0


In [39]:
from sklearn.metrics import confusion_matrix
print (confusion_matrix(classifier.predict(test),t_test))

[[11  0  0]
 [ 0 13  0]
 [ 0  0  6]]


In [40]:
from sklearn.metrics import classification_report
print (classification_report(classifier.predict(test), t_test,
target_names=['setosa', 'versicolor', 'virginica']))

             precision    recall  f1-score   support

     setosa       1.00      1.00      1.00        11
 versicolor       1.00      1.00      1.00        13
  virginica       1.00      1.00      1.00         6

avg / total       1.00      1.00      1.00        30



## n_estimators=15

In [46]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators=15)

In [47]:
from sklearn import cross_validation
train, test, t_train, t_test = cross_validation.train_test_split(data, t, test_size=0.2, random_state=0)

In [48]:
classifier.fit(train,t_train) # train
print (classifier.score(test,t_test)) # test

0.966666666667


In [49]:
from sklearn.metrics import confusion_matrix
print (confusion_matrix(classifier.predict(test),t_test))

[[11  0  0]
 [ 0 13  1]
 [ 0  0  5]]


In [50]:
from sklearn.metrics import classification_report
print (classification_report(classifier.predict(test), t_test,
target_names=['setosa', 'versicolor', 'virginica']))

             precision    recall  f1-score   support

     setosa       1.00      1.00      1.00        11
 versicolor       1.00      0.93      0.96        14
  virginica       0.83      1.00      0.91         5

avg / total       0.97      0.97      0.97        30

